sonar.projectKey=app-reservas-monorepo
sonar.projectName=App Reservas Monorepo
sonar.projectVersion=1.0.0
sonar.sources=auth-service,booking-service,user-service,notification-service,frontend
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/*.spec.js,**/*.test.js
sonar.tests=auth-service,booking-service,user-service,notification-service,frontend
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
